# Generated by Django 5.2 on 2025-04-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='itineraries.hotel'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='itineraries.day'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='itineraries.hotel'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='mode',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat')], default='Car', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='itineraries.hotel'),
        ),
    ]
