# Generated by Django 5.2 on 2025-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_activity_hotel_alter_transfer_day_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_location'], name='itineraries_from_lo_89b8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_location'], name='itineraries_to_loca_7bbe00_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['mode'], name='itineraries_mode_59aec6_idx'),
        ),
    ]
